package main;
// Generated 25 Apr, 2019 8:03:08 PM by Hibernate Tools 4.3.1



/**
 * AdminInfo generated by hbm2java
 */
public class AdminInfo  implements java.io.Serializable {


     private long adminAadhar;
     private String adminName;
     private String adminEmail;
     private long adminContact;
     private String adminAddress;
     private String adminPhoto;
     private String adminUsername;
     private String adminPassword;

    public AdminInfo() {
    }

    public AdminInfo(long adminAadhar, String adminName, String adminEmail, long adminContact, String adminAddress, String adminPhoto, String adminUsername, String adminPassword) {
       this.adminAadhar = adminAadhar;
       this.adminName = adminName;
       this.adminEmail = adminEmail;
       this.adminContact = adminContact;
       this.adminAddress = adminAddress;
       this.adminPhoto = adminPhoto;
       this.adminUsername = adminUsername;
       this.adminPassword = adminPassword;
    }
   
    public long getAdminAadhar() {
        return this.adminAadhar;
    }
    
    public void setAdminAadhar(long adminAadhar) {
        this.adminAadhar = adminAadhar;
    }
    public String getAdminName() {
        return this.adminName;
    }
    
    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }
    public String getAdminEmail() {
        return this.adminEmail;
    }
    
    public void setAdminEmail(String adminEmail) {
        this.adminEmail = adminEmail;
    }
    public long getAdminContact() {
        return this.adminContact;
    }
    
    public void setAdminContact(long adminContact) {
        this.adminContact = adminContact;
    }
    public String getAdminAddress() {
        return this.adminAddress;
    }
    
    public void setAdminAddress(String adminAddress) {
        this.adminAddress = adminAddress;
    }
    public String getAdminPhoto() {
        return this.adminPhoto;
    }
    
    public void setAdminPhoto(String adminPhoto) {
        this.adminPhoto = adminPhoto;
    }
    public String getAdminUsername() {
        return this.adminUsername;
    }
    
    public void setAdminUsername(String adminUsername) {
        this.adminUsername = adminUsername;
    }
    public String getAdminPassword() {
        return this.adminPassword;
    }
    
    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword;
    }




}


